version: "3"
services:
  backend:
    build: .
    command: ["bin/url_shortener", "start"]
    environment:
      - SECRET_KEY_BASE=verylongstringhere
      - DATABASE_URL=ecto://postgres:postgres@db/url_shortener
    ports:
      - "4000:4000"

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata:
